FROM python:2.7
ENV PYTHONUNBUFFERED 1

COPY ./requirements.txt /app/requirements.txt

RUN pip install -r /app/requirements.txt

USER nobody

EXPOSE 8000
WORKDIR /app


CMD gunicorn --workers 3 --bind 0.0.0.0:8000 webapp:app --chdir=/app/flapp --log-level DEBUG
